version: '3.8'

services:
  internetbanking:
    image: priyankadevops6304/internetbanking:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/internetbanking:/usr/share/nginx/html

  mobilebanking:
    image: priyankadevops6304/mobilebanking:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/mobilebanking:/usr/share/nginx/html

  insurance:
    image: priyankadevops6304/insurance:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/insurance:/usr/share/nginx/html

  loans:
    image: priyankadevops6304/loans:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/loans:/usr/share/nginx/html
